Allow potentially long names,tags and addresses to still be seen in UI
AY2223S2-CS2103T-W10-3/tp pull request #143
Opened 2023-04-01 15:08 UTC by minosx31

Enable text wrap for names,tags and address, with rank still remaining infront of name.

Before resize:
![image](https://user-images.githubusercontent.com/77110390/229297252-1e3a6b23-a62b-4651-b087-ce2c1a8fc7e7.png)

After resize:
![image](https://user-images.githubusercontent.com/77110390/229297263-05755341-b02e-42c0-abdc-57e5f083d7bf.png)

Fixes #106 
Fixes #120 
Fixes #129

2023-04-02 02:29 UTC, rexcyrio commented
What happens if I have 50 tags? Do all the 50 tags line up in a horizontal row such that all 50 tags will be displayed to the user? Will the tag be too narrow to read the tag name properly?

2023-04-02 04:41 UTC, minosx31 commented
> What happens if I have 50 tags? Do all the 50 tags line up in a horizontal row such that all 50 tags will be displayed to the user? Will the tag be too narrow to read the tag name properly?

The current implementation will try to squeeze all 50 tags in a single row but this would mean that the text inside is wrapped in such a way that it may not be readable. 

![image](https://user-images.githubusercontent.com/77110390/229331653-e3b546d6-4c48-4dac-9168-d39fcd44d48c.png)



I could change it back such that the tags would still flow nicely and remain readable but would probably need to set a length restriction for the tags.
![image](https://user-images.githubusercontent.com/77110390/229331681-53e04c82-1b56-47e3-8d21-52e9141cca47.png)

2023-04-02 06:51 UTC, rexcyrio commented
For long names, we can simply let the text break to the next line -- is this possible for tags too (i.e., a very long tag name breaks to the next line)? Though, I am worried that it may not be viewed as a single tag item anymore cause of the line break *within* the light blue tag box.

Alternatively, maybe we can just set the max length for tags at 100 alphanumeric characters? Then we won't face the overflow issue anymore.

2023-04-07 01:21 UTC, rexcyrio requested changes

2023-04-07 01:21 UTC, rexcyrio commented on src/main/java/seedu/address/model/tag/Tag.java
> +     * @return
Missing JavaDocs here

2023-04-07 01:21 UTC, rexcyrio commented on src/main/java/seedu/address/model/tag/Tag.java
> +     * Returns true if a given string is at most 100 characters long.
Is it `100 characters` or `60 characters`?

2023-04-07 01:21 UTC, rexcyrio commented on src/main/java/seedu/address/storage/JsonAdaptedTag.java
> +            throw new ParseException(Tag.MESSAGE_LENGTH_CONSTRAINTS);
Do we want to throw a `ParseException` or an `IllegalValueException`?

In `JsonAdaptedPerson.java`:

```java
public Person toModelType() throws IllegalValueException {
    /* calls JsonAdaptedTag::toModelType() */
}
```

2023-04-07 01:21 UTC, rexcyrio commented on src/main/java/seedu/address/storage/JsonAdaptedTag.java
>      public Tag toModelType() throws IllegalValueException {
See my comment below -- both the JavaDocs and method signature `throws XYZException` may need to be updated.

2023-04-08 14:01 UTC, minosx31 commented on src/main/java/seedu/address/model/tag/Tag.java
> +    }
Yeah good suggestion! Will add them in the next commit 😃

2023-04-09 02:00 UTC, rexcyrio requested changes

2023-04-09 08:50 UTC, rexcyrio approved these changes
LGTM :+1:

2023-04-09 09:16 UTC, merged