update DG favorites
AY2223S2-CS2103T-W10-3/tp pull request #166
Opened 2023-04-08 15:02 UTC by jugheadjones10

2023-04-09 01:17 UTC, rexcyrio requested changes

2023-04-09 01:17 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +that have the `isFavorite` field set to `true`.
> filter out all the `Person` objects that have the `isFavorite` field set to `true`.

To me, the word "filter" has the notion of "removing" -- I'm not sure if the user will mistakenly read this line as 

> **remove** all the `Person` objects that have the `isFavorite` field set to `true`

which is clearly not what was intended

---

Maybe we can say the following?

> it uses a predicate to **pick out** / **select** / **choose** all the `Person` objects that have the `isFavorite` field set to `true`

2023-04-09 01:17 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +is `false`) and `false` if it is `true`.
I think we should inform the reader explicitly about the "toggle" behaviour rather than say "if `true`, it'll become `false`; if `false`, it'll become `true`" to help them better understand what is happening

2023-04-09 01:17 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +#### Favorite: Current implementation
Remember to update TOC!

2023-04-09 05:45 UTC, jugheadjones10 commented on docs/DeveloperGuide.md
> +is `false`) and `false` if it is `true`.
Agreed, have changed the wording in latest push.

2023-04-09 08:54 UTC, rexcyrio requested changes

2023-04-09 08:54 UTC, rexcyrio commented on docs/DeveloperGuide.md
>  a `FavoriteCommand`, the `isFavorite` field of the specified `Person` will be set to `true`.
I think the "toggle" behaviour should be added on this line too (i.e., it is incorrect to say that when the user executes a `FavoriteCommand`, the `isFavorite` field of the specified `Person` will **always** be set to `true`)

2023-04-10 01:25 UTC, rexcyrio requested changes

2023-04-10 01:25 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +is `false` and `false` if it is `true`.
It sounds like we're repeating ourselves here -- maybe we can consolidate these few lines together to be more coherent

2023-04-10 10:08 UTC, rexcyrio approved these changes
LGTM :+1:

2023-04-10 11:34 UTC, merged