Update UG introduction and purpoes
AY2223S2-CS2103T-W10-3/tp pull request #175
Opened 2023-04-09 15:35 UTC by niekis

2023-04-09 16:45 UTC, minosx31 requested changes
Minor typos present 😆

2023-04-09 16:45 UTC, minosx31 commented on docs/UserGuide.md
> +
Extra linebreak?

2023-04-09 16:45 UTC, minosx31 commented on docs/UserGuide.md
> +AIMS is optimized for use via a Command Line Interface** (**CLI**) while still having the benefits of a Graphical
Missing `**` infront of "Command Line Interface"

2023-04-09 16:45 UTC, minosx31 commented on docs/UserGuide.md
>  User Interface (**GUI**). If you can type fast, AIMS can get your contact management tasks done faster than traditional
Could bold "Graphical User Interface" too since "GUI" is bolded also

2023-04-09 16:45 UTC, minosx31 commented on docs/UserGuide.md
> +AIMS is intended to make your life easier. With an emphasis of proper checking and validation of contact information, AIMS eradicates time wasted on dealing with erroneous data and ensures that conta
Makes me want to use AIMS after reading this!

2023-04-10 02:21 UTC, rexcyrio requested changes

2023-04-10 02:21 UTC, rexcyrio commented on docs/UserGuide.md
> +For a more technical and comprehesive overview of AIMS's codebase, please refer to our [Developer Guide.](DeveloperGuide.md)
Spelling error: comprehe***n***sive

2023-04-10 02:21 UTC, rexcyrio commented on docs/UserGuide.md
> +GUI apps.
Do we want to put this section next to the **Purpose** section?

See https://ay2223s1-cs2103t-w10-3.github.io/tp/UserGuide.html -- they put **What is TrackAScholar?** and **Who is this User Guide for?** (i.e., the purpose of the UG) next to each other to avoid repeating themselves too much

2023-04-10 06:17 UTC, niekis commented on docs/UserGuide.md
> +GUI apps.
sure!

2023-04-10 10:10 UTC, rexcyrio requested changes

2023-04-10 10:10 UTC, rexcyrio commented on docs/UserGuide.md
> +## Table of Contents\
Erroneous `\`

2023-04-10 12:09 UTC, minosx31 commented on docs/UserGuide.md
> +</div>
I think can 'tab' this block so it is pushed in together with the bullet point. Same for the below pics

2023-04-10 12:17 UTC, rexcyrio requested changes

2023-04-10 12:17 UTC, rexcyrio commented on docs/UserGuide.md
> +4. Open AIMS. Into the command line input `importcsv ` followed by pasting the path to the CSV file. Remove any inverted commas at the front and end of the path that might be added by copy and pastin
I think we should standardise and call it the "command box" (see the AIMS GUI overview screenshot)

2023-04-10 12:17 UTC, rexcyrio commented on docs/UserGuide.md
> +![importcsv success](images/demoImportcsvSuccess.png)
I think we can remove this line as the picture is already shown using the `div` just below

2023-04-10 12:43 UTC, rexcyrio approved these changes
LGTM :+1:

2023-04-10 12:47 UTC, minosx31 approved these changes

2023-04-10 12:47 UTC, merged