Update manual testing section in DG
AY2223S2-CS2103T-W10-3/tp pull request #176
Opened 2023-04-09 16:40 UTC by minosx31

2023-04-09 16:41 UTC, minosx31 commented on docs/DeveloperGuide.md
> +- Libraries used: [JavaFX](https://openjfx.io/), [Jackson](https://github.com/FasterXML/jackson), [JUnit5](https://github.com/junit-team/junit5)
@niekis you might wanna add Opencsv here. Can also provide me the source link so that I can add in for you

2023-04-10 01:29 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +- Libraries used: [JavaFX](https://openjfx.io/), [Jackson](https://github.com/FasterXML/jackson), [JUnit5](https://github.com/junit-team/junit5)
https://opencsv.sourceforge.net

Source: https://github.com/nus-cs2103-AY2223S2/forum/issues/271

2023-04-10 02:29 UTC, rexcyrio requested changes

2023-04-10 02:29 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +   1. Prerequisites: List all persons using the `list` command. Multiple persons in the list.
I think another prerequisite should be that there are no currently favorited persons in the favorites list.

2023-04-10 02:29 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +   1. Prerequisite: Delete the `aims.json` file in `./data` folder and launch AIMS again.<br>
> Delete the `aims.json` file in `./data` folder and launch AIMS again.

This sounds like the test case itself

I think for the prerequisite we can say that "the `aims.json` file exists in the `./data` folder"

2023-04-10 02:29 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +      Expected: AIMS loads a default list of persons and the data file is created again.
Do note that the new `aims.json` data file is only created **after** the user exits the app (i.e., when the user is still using the app, the newly created `aims.json` does not exist on disk yet)

2023-04-10 09:43 UTC, minosx31 commented on docs/DeveloperGuide.md
> +   Expected: Error details shown in the message box, indicating that duplicate emails or phones are not allowed.
I was following their format hehe but ig i can add a note for this?

2023-04-10 10:23 UTC, rexcyrio approved these changes
LGTM :+1:

2023-04-10 10:48 UTC, merged