Add Rank, Unit, Company, Platoon fields
AY2223S2-CS2103T-W10-3/tp pull request #42
Opened 2023-03-08 06:45 UTC by jugheadjones10

closes #38

2023-03-08 09:45 UTC, rexcyrio commented on src/test/java/seedu/address/testutil/TypicalPersons.java
> +            .withEmail("lydia@example.com").withAddress("little tokyo").withRank("private").build();
I think `"private"` should be `"PTE"`

2023-03-08 09:46 UTC, rexcyrio commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +    public static final String DEFAULT_RANK = "private";
I think `"private"` should be `"PTE"`

2023-03-08 09:51 UTC, rexcyrio commented on src/test/java/seedu/address/testutil/TypicalPersons.java
> +            .withEmail("stefan@example.com").withAddress("little india").withRank("private").build();
I think `"private"` should be `"PTE"`

2023-03-09 08:37 UTC, niekis requested changes
I think you might be missing some test cases, especially there should probably be one under test/java/seedu/address/model/person/RankTest
maybe can just look through the [tutorial 2](https://nus-cs2103-ay2223s2.github.io/tp/tutorials/AddRemark.html) to see if you're missing any other tests

2023-03-10 05:44 UTC, minosx31 commented
> Speaking of test cases, I also noted that some of the Gradle test cases failed. Are those test cases still relelvant? Should the code / test cases be modified such that all the test cases pass?

Yeah, I think need to take a look at the test cases and see if can modify to fit the change

2023-03-10 14:27 UTC, jugheadjones10 commented
@rexcyrio @minosx31 @niekis 
Fixed all tests broken by the new fields, Gradle is building now. Regarding field-specific tests, maybe we can add those in future iterations?

2023-03-11 02:12 UTC, rexcyrio requested changes

2023-03-11 02:12 UTC, rexcyrio commented on src/main/resources/view/PersonListCard.fxml
> +<?import javafx.scene.layout.*?>
I think we should use explicit imports here.

2023-03-11 02:12 UTC, rexcyrio commented on src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> +            DeleteCommand.COMMAND_WORD + " " + INDEX_FIRST_PERSON.getOneBased());
Remember to set the continuation indent in `Settings > Editor > Code Style > Java > Tabs and Indents` to 8 spaces! (see [the CS2103T Java coding standard](https://se-education.org/guides/conventions/java/intermediate.html#:~:text=Indentation%20for%20wrapped%20lines%20should%20be%208%20spaces))

2023-03-11 02:26 UTC, rexcyrio commented
> @rexcyrio @minosx31 @niekis Fixed all tests broken by the new fields, Gradle is building now. Regarding field-specific tests, maybe we can add those in future iterations?

I think we should add the test cases for `Rank` now rather than in future iterations.

It doesn't really make sense to "accept" a new feature only to introduce test cases for the feature later on -- are we saying that we accepted a potentially buggy feature previously?

Maybe one good test case to have is to check whether we accept `"pte"` (i.e., lowercase characters instead of uppercase characters).

2023-03-11 14:28 UTC, jugheadjones10 commented
> > @rexcyrio @minosx31 @niekis Fixed all tests broken by the new fields, Gradle is building now. Regarding field-specific tests, maybe we can add those in future iterations?
> 
> I think we should add the test cases for `Rank` now rather than in future iterations.
> 
> It doesn't really make sense to "accept" a new feature only to introduce test cases for the feature later on -- are we saying that we accepted a potentially buggy feature previously?
> 
> Maybe one good test case to have is to check whether we accept `"pte"` (i.e., lowercase characters instead of uppercase characters).

True. I'll add the tests.

2023-03-12 02:50 UTC, rexcyrio requested changes
I think you accidentally committed the `/bin` folder to the repo. 

To fix this:

1. delete the `/bin` folder and commit
1. add the following line to `.gitignore` and commit

```gitignore
# VS Code Red Hat Java build files
/bin/
```

([Referenced from StackOverflow](https://stackoverflow.com/questions/28388597/removing-bin-executable-folder-from-github))

You can also consider disabling the "autobuild" functionality of Red Hat Java so that it'll stop creating the `/bin` folder for you automatically.

![Code_I4vr9lQnz6](https://user-images.githubusercontent.com/76687125/224522277-575c0e93-83fd-44ab-b96a-4ca242216831.png)

2023-03-12 02:50 UTC, rexcyrio commented on src/test/java/seedu/address/model/person/RankTest.java
> +        assertThrows(IllegalArgumentException.class, () -> new Email(invalidRank));
I think you meant to test `Rank(invalidRank)` here instead of `Email(invalidRank)`

2023-03-13 13:43 UTC, merged