Update UG to include copy command
AY2223S2-CS2103T-W10-3/tp pull request #59
Opened 2023-03-18 06:03 UTC by minosx31

2023-03-19 00:59 UTC, rexcyrio commented on docs/UserGuide.md
> +- `copy 3`
Do we want to have more "real" examples in the user guide? I was thinking something along the lines of:

"
Suppose Jacob Lim is at position 3 with email jacoblim@yahoo.com, phone number 97671263, /\*other information\*/. After you run `copy 3`, the following text will be copied to your clipboard:

```text
Name: Jacob Lim
Email: jacoblim@yahoo.com
Phone number: 97671263
/* other fields */
```

Note: if the FAILS is unable to access your clipboard, it will display all the person's information in the *forgot-what-name* box. You can then highlight the text using the mouse and copy it to your clipboard using `Ctrl + C` on Windows/Linux or `Command + C` on Mac.
"

With regards to the last point, I also thought it would be good to tell the user what FAILS would do if it couldn't access the clipboard. After all, where else are we going to tell the user about this fall-back function?

2023-03-19 15:06 UTC, niekis reviewed
mostly looks good!

2023-03-19 15:06 UTC, niekis commented on docs/UserGuide.md
> +- Copies the information of the person at the specified `INDEX`.
can mention that it copies to clipboard here + maybe the need for clipboard? (i agree w stefan)

2023-03-19 15:06 UTC, niekis commented on docs/UserGuide.md
> +- `copy 3`
can add a tip here! like how you can find/filter first and then copy to easily copy what you need

2023-03-27 14:25 UTC, niekis requested changes
mostly good!

2023-03-27 14:25 UTC, niekis commented on docs/UserGuide.md
> +### Copy information of a person : `copy`
maybe change title to "Copy information to clipboard"?

2023-03-27 14:33 UTC, niekis approved these changes
LGTM!

2023-03-27 14:33 UTC, niekis commented on docs/images/copy2Result.png
nice! thanks for the change

2023-03-27 14:33 UTC, merged