Update DG to include implementation of `Copy` feature
AY2223S2-CS2103T-W10-3/tp pull request #65
Opened 2023-03-23 11:43 UTC by minosx31

2023-03-23 14:04 UTC, rexcyrio commented on docs/DeveloperGuide.md
> +### Copy to clipboard
Is the table of contents updated?

2023-03-23 16:04 UTC, minosx31 commented on docs/DeveloperGuide.md
> +### Copy to clipboard
Ah missed that out

2023-03-24 03:03 UTC, rexcyrio approved these changes
LGTM :+1:

2023-03-24 03:04 UTC, merged

2023-03-24 03:10 UTC, niekis requested changes
looks pretty good, just some minor comments that could make our DG look more stanardized

2023-03-24 03:10 UTC, niekis commented on docs/images/CopySequenceDiagram.png
when `CopyCommand` returns to `AddressBookParser`, I think you're missing a 'c' label on the return arrow.

2023-03-24 03:10 UTC, niekis commented on docs/images/CopySequenceDiagram.png
You could also add a 'result' label on the return arrow from `CopyCommand` to `LogicManager`, like in the `delete` diagram

2023-03-24 03:10 UTC, niekis commented on docs/DeveloperGuide.md
> +The copy feature is implemented by extracting information of the specified `Person` and then setting it as the content of the user's system's clipboard. The copy mechanism is facilitated by `CopyComm
Not sure if it's relevant, but you could briefly explain how you copied it to clipboard?

2023-03-24 03:52 UTC, rexcyrio commented
@niekis I think you can open a new issue with label `type.Bug` that references these comments so that @minosx31 can recitfy them properly (I can't find a way to re-open a PR that has already been merged lol)