Implement favorites without adding tests
AY2223S2-CS2103T-W10-3/tp pull request #78
Opened 2023-03-26 07:23 UTC by jugheadjones10

2023-03-29 09:34 UTC, rexcyrio requested changes

2023-03-29 09:34 UTC, rexcyrio commented on src/main/java/seedu/address/model/person/Person.java
> +    private Boolean isFavorite = false;
See comment on wrapper class `Boolean`

2023-03-29 09:34 UTC, rexcyrio commented on src/main/java/seedu/address/model/person/Person.java
> +    public Boolean getIsFavorite() {
Likewise, see comment on wrapper class `Boolean`

2023-03-29 09:37 UTC, rexcyrio commented on src/main/java/seedu/address/logic/commands/FavoriteCommand.java
> +        model.updateFavoritedPersonList();
This has been resolved in the commit "Add tests for favorite command".

2023-03-29 09:38 UTC, rexcyrio commented on src/main/java/seedu/address/model/Model.java
> +    void updateFavoritedPersonList();
This has been resolved in the commit "Add tests for favorite command".

2023-03-30 18:39 UTC, merged

2023-04-02 04:09 UTC, jugheadjones10 commented on src/main/java/seedu/address/ui/FavoritesListPanel.java
> +                setGraphic(new PersonCard(person, filteredListPersonIndex + 1).getRoot());
Fixed this as part of fixing a similar bug discovered in PED

2023-04-02 09:28 UTC, rexcyrio commented
Comments that are currently not yet resolved:
- https://github.com/AY2223S2-CS2103T-W10-3/tp/pull/78#discussion_r1148523979
- https://github.com/AY2223S2-CS2103T-W10-3/tp/pull/78#discussion_r1148527472